version: "3.5"
services:
  elasticsearch:
    hostname: "${WARDEN_ENV_NAME}-elasticsearch"
    image: ${WARDEN_IMAGE_REPOSITORY}/elasticsearch:${ELASTICSEARCH_VERSION:-7.9}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-elasticsearch.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-elasticsearch.rule=Host(`elasticsearch.${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-elasticsearch.loadbalancer.server.port=9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms${WARDEN_ELASTICSEARCH_JAVA_XMS:-512m} -Xmx${WARDEN_ELASTICSEARCH_JAVA_XMX:-512m}"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - index.blocks.read_only_allow_delete
    volumes:
      - esdata:/usr/share/elasticsearch/data

  elasticsearch-hq:
    hostname: "${WARDEN_ENV_NAME}-elasticsearch-hq"
    image: elastichq/elasticsearch-hq:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-elasticsearch-hq.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-elasticsearch-hq.rule=Host(`elastichq.${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-elasticsearch-hq.loadbalancer.server.port=5000
    environment:
      - HQ_DEFAULT_URL=http://elasticsearch:9200
volumes:
  esdata:
