version: "3.5"
services:
  nginx:
    hostname: "${WARDEN_ENV_NAME}-nginx"
    image: ${WARDEN_IMAGE_REPOSITORY}/nginx:${NGINX_VERSION:-1.16}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.priority=2
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.rule=
          HostRegexp(`{subdomain:.+}.${TRAEFIK_DOMAIN}`) || Host(`${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-nginx.loadbalancer.server.port=80
      - traefik.docker.network=${WARDEN_ENV_NAME}_default
    volumes:
      - .${WARDEN_WEB_ROOT:-}/:/var/www/html:cached
    environment:
      - FORCE_DEBUG=${WARDEN_FORCE_DEBUG:-}
      - XDEBUG_CONNECT_BACK_HOST=${XDEBUG_CONNECT_BACK_HOST:-''}
