name: Docker Image Varnish
on:
  schedule:
  - cron: "0 6 1 * *"   # 6 AM UTC on 1st day of month
  push:
    paths:
    - version
    - images/.trigger
    - images/varnish/**
    branches:
    - main
  workflow_dispatch:
jobs:
  varnish:
    name: Varnish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
      env:
        BUILD_GROUP: varnish
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        WARDEN_IMAGE_REPOSITORY: ${{ secrets.IMAGE_REPOSITORY }}
