name: Docker Image Magepack
on:
  schedule:
    - cron: "0 6 1 * *" # 6 AM UTC on 1st day of month
  push:
    paths:
      - version
      - images/.trigger
      - images/magepack/**
      - .github/workflows/*magepack*

jobs:
  magepack:
    name: Magepack
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "2.3"

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v2
        with:
          context: images/magepack
          platforms: linux/amd64,linux/arm64
          build-args: MAGEPACK_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/wardenenv/magepack:${{ matrix.version }}
