name: Docker Image PHP-FPM
on:
  schedule:
  - cron: "0 6 1 * *"   # 6 AM UTC on 1st day of month
  push:
    paths:
    - version
    - images/.trigger
    - images/php-fpm/**
    branches:
    - main
  workflow_dispatch:
jobs:
  php-fpm:
    name: FPM ${{ matrix.php_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.2", "7.3", "7.4", "8.0", "8.1"]
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
      env:
        BUILD_GROUP: php-fpm
        PHP_VERSION: ${{ matrix.php_version }}
        PHP_VARIANT: ${{ matrix.php_variant }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        WARDEN_IMAGE_REPOSITORY: ${{ secrets.IMAGE_REPOSITORY }}

  laravel:
    name: PHP-FPM ${{ matrix.php_version }} (laravel)
    runs-on: ubuntu-latest
    needs: php-fpm
    strategy:
      matrix:
        php_version: ["7.2", "7.3", "7.4", "8.0", "8.1"]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
        env:
          BUILD_GROUP: php-fpm/laravel
          PHP_VERSION: ${{ matrix.php_version }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          WARDEN_IMAGE_REPOSITORY: ${{ secrets.IMAGE_REPOSITORY }}

  magento1:
    name: PHP-FPM ${{ matrix.php_version }} (magento1)
    runs-on: ubuntu-latest
    needs: php-fpm
    strategy:
      matrix:
        php_version: ["7.2", "7.3", "7.4", "8.0", "8.1"]
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
      env:
        BUILD_GROUP: php-fpm/magento1
        PHP_VERSION: ${{ matrix.php_version }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        WARDEN_IMAGE_REPOSITORY: ${{ secrets.IMAGE_REPOSITORY }}

  magento2:
    name: PHP-FPM ${{ matrix.php_version }} (magento2)
    runs-on: ubuntu-latest
    needs: php-fpm
    strategy:
      matrix:
        php_version: ["7.2", "7.3", "7.4", "8.0", "8.1"]
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
      env:
        BUILD_GROUP: php-fpm/magento2
        PHP_VERSION: ${{ matrix.php_version }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        WARDEN_IMAGE_REPOSITORY: ${{ secrets.IMAGE_REPOSITORY }}
