name: Docker Image Elasticsearch
on:
  schedule:
    - cron: "0 6 1 * *" # 6 AM UTC on 1st day of month
  push:
    paths:
      - version
      - images/.trigger
      - images/elasticsearch/**
      - .github/workflows/*elasticsearch*

jobs:
  elasticsearch:
    name: Elasticsearch
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "7.10"
          - "7.12"
          - "7.13"
          - "7.14"
          - "7.15"
          - "7.16"
          - "7.17"
          - "8.0"
          - "8.1"

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Set build-args
        run: |-
          ESCAPED_VERSION="$(echo ${{ matrix.version }} | sed 's/\./\\\./g')"
          ES_VERSION=$(
            docker run --rm gcr.io/go-containerregistry/crane:v0.8.0 ls docker.elastic.co/elasticsearch/elasticsearch \
            | egrep "^${ESCAPED_VERSION}\.[0-9]+\$" | sort -Vr | head -n1
          )
          echo "ES_VERSION=${ES_VERSION}" | tee /dev/stderr >> $GITHUB_ENV

      - uses: docker/build-push-action@v2
        with:
          context: images/elasticsearch
          platforms: linux/amd64,linux/arm64
          build-args: ES_VERSION=${{ env.ES_VERSION }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/wardenenv/elasticsearch:${{ matrix.version }}
