name: Docker Image OpenSearch
on:
  schedule:
    - cron: "0 6 1 * *" # 6 AM UTC on 1st day of month
  push:
    paths:
      - version
      - images/.trigger
      - images/opensearch/**
      - .github/workflows/*opensearch*

jobs:
  opensearch:
    name: OpenSearch
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.1"
          - "1.2"
          - "1.3"

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Set build-args
        run: |-
          ESCAPED_VERSION="$(echo ${{ matrix.version }} | sed 's/\./\\\./g')"
          OPENSEARCH_VERSION=$(
            docker run --rm gcr.io/go-containerregistry/crane:v0.8.0 ls docker.io/opensearchproject/opensearch \
            | egrep "^${ESCAPED_VERSION}\.[0-9]+\$" | sort -Vr | head -n1
          )
          echo "OPENSEARCH_VERSION=${OPENSEARCH_VERSION}" | tee /dev/stderr >> $GITHUB_ENV

      - uses: docker/build-push-action@v2
        with:
          context: images/opensearch
          platforms: linux/amd64,linux/arm64
          build-args: OPENSEARCH_VERSION=${{ env.OPENSEARCH_VERSION }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/wardenenv/opensearch:${{ matrix.version }}
