name: Docker Image Varnish
on:
  schedule:
    - cron: "0 6 1 * *" # 6 AM UTC on 1st day of month
  push:
    paths:
      - version
      - images/.trigger
      - images/varnish/**
      - .github/workflows/*varnish*

jobs:
  varnish:
    name: Varnish
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "6.0"
          - "6.5"
          - "6.6"
          - "7.0"
          - "7.1"
        include:
          - version: "6.0"
            suffix: "lts"

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Set build-args
        run: |-
          VARNISH_VERSION="$(echo ${{ matrix.version }} | tr -d .)${{ matrix.suffix }}"
          echo "VARNISH_VERSION=${VARNISH_VERSION}" | tee /dev/stderr >> $GITHUB_ENV

      - uses: docker/build-push-action@v2
        with:
          context: images/varnish
          platforms: linux/amd64,linux/arm64
          build-args: VARNISH_VERSION=${{ env.VARNISH_VERSION }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/ytorbyk/varnish:${{ matrix.version }}
