name: Docker Image MariaDB
on:
  schedule:
  - cron: "0 6 1 * *"   # 6 AM UTC on 1st day of month
  push:
    paths:
    - version
    - images/.trigger
    - images/mariadb/**
    branches:
    - main
  workflow_dispatch:
jobs:
  mariadb:
    name: MariaDB
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
      env:
        BUILD_GROUP: mariadb
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        WARDEN_IMAGE_REPOSITORY: ${{ secrets.IMAGE_REPOSITORY }}
