name: Docker Image Redis
on:
  schedule:
    - cron: "0 6 1 * *" # 6 AM UTC on 1st day of month
  push:
    paths:
      - version
      - images/.trigger
      - images/redis/**
      - .github/workflows/*redis*

jobs:
  redis:
    name: Redis
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "3.2"
          - "4.0"
          - "5.0"
          - "6.0"
          - "6.2"

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v2
        with:
          context: images/redis
          platforms: linux/amd64,linux/arm64
          build-args: REDIS_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/wardenenv/redis:${{ matrix.version }}
