name: "Push Release to Brew"
on:
  release:
    types: [published]
jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ github.repository_owner }}/homebrew-warden
      - name: 'Update Version'
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |-
          sudo apt-get install -y curl libdigest-sha-perl gettext-base
          curl "https://codeload.github.com/${{ github.repository_owner }}/warden/tar.gz/refs/tags/${VERSION}" -o release.tar.gz
          export HASH=$(shasum -a256 release.tar.gz | head -n1 | awk '{print $1;}')
          envsubst '$HASH,$VERSION' < Formula/warden.rb.template > Formula/warden.rb
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add Formula/warden.rb
          git commit -m "Mark v${VERSION}"
          git push
